

services:
  nginx:
    image: nginx:stable
    container_name: valet-key-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-error-pages:/usr/share/nginx/html/error:ro
      - ./ssl:/etc/nginx/ssl:ro

  backend1:
    build: .
    container_name: valet-key-backend-1
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "./target/demo-0.0.1-SNAPSHOT.jar:/app/app.jar"
      - ./application-prod.properties:/app/application-prod.properties
    command: >
      sh -c "java -jar app.jar --spring.config.additional-location=file:/app/ --spring.profiles.active=prod"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8080"
#    extra_hosts:
#      - "nguyentanstorage.blob.core.windows.net:127.0.0.1"


  backend2:
    build: .
    container_name: valet-key-backend-2
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "./target/demo-0.0.1-SNAPSHOT.jar:/app/app.jar"
      - ./application-prod.properties:/app/application-prod.properties
    command: >
      sh -c "java -jar app.jar --spring.config.additional-location=file:/app/ --spring.profiles.active=prod"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8080"
#    extra_hosts:
#      - "nguyentanstorage.blob.core.windows.net:127.0.0.1"


  backend3:
    build: .
    container_name: valet-key-backend-3
    ports:
      - "8083:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "./target/demo-0.0.1-SNAPSHOT.jar:/app/app.jar"
      - ./application-prod.properties:/app/application-prod.properties
    command: >
      sh -c "java -jar app.jar --spring.config.additional-location=file:/app/ --spring.profiles.active=prod"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8080"
#    extra_hosts:
#      - "nguyentanstorage.blob.core.windows.net:127.0.0.1"


  db:
    image: mysql:8
    container_name: valet_key_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret" ]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 10s
  
  redis:
    image: redis:7-alpine
    container_name: valet_key_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  redis_data: